#pragma once

enum EventType {
    LOBBY_CREATED = 0,
    LOBBY_CREATEFAILED,
    LOBBY_SEARCHCOMPLETED,
    LOBBY_JOINED,
    LOBBY_JOINFAILED,

    LEAVE_CURRENT_LOBBY,
    START_AS_SERVER,
    START_AS_CLIENT,
    MAX_EVENT_TYPE,

    PROJECTILE_PORTAL_COLLISION
};