#pragma once

enum EventType {
    LOBBY_CREATED = 0,
    LOBBY_CREATEFAILED,
    LOBBY_SEARCHCOMPLETED,
    LOBBY_JOINED,
    LOBBY_JOINFAILED,
    LOBBY_GAMESTART,
    LOBBY_LEAVE,

    ROUND_OVER,

    START_AS_SERVER,
    START_AS_CLIENT,
    MAX_EVENT_TYPE
};