#pragma once

enum EventType {
    LOBBY_CREATED = 0,
    LOBBY_CREATEFAILED,
    LOBBY_SEARCHCOMPLETED,
    LOBBY_JOINED,
    LOBBY_JOINFAILED,
    LOBBY_GAMESTART,
    LOBBY_LEAVE,

    ROUND_OVER,

    START_AS_SERVER,
    START_AS_CLIENT,
    MAX_EVENT_TYPE,

    ACTIVATE_NONE_POWER_UP,
    ACTIVATE_ICE_POWER_UP,
    ACTIVATE_SAND_POWER_UP,
    ACTIVATE_WIND_POWER_UP,

    PROJECTILE_PORTAL_COLLISION
};